### ISSUE TITLE
Error: Cannot find module './src/kahoot.js'

### ISSUE THREAD

**Issue by anonymousomeone** [collin9ex/kahoot-spam#1]
i get this error when running node kahootspam.js
`Error: Cannot find module './src/kahoot.js'
Require stack:
- C:\Users\stsce\node_modules\kahoot.js-updated\index.js
- C:\Users\stsce\Desktop\wasd\kahootspam.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:88:18)[39m
    at Object.<anonymous> (C:\Users\stsce\node_modules\[4mkahoot.js-updated[24m\index.js:1:16)
[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:928:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:952:19)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\stsce\\node_modules\\kahoot.js-updated\\index.js'[39m,
    [32m'C:\\Users\\stsce\\Desktop\\wasd\\kahootspam.js'[39m
  ]
}`

**Comment by Cheesegle** [comment]
I replicated this issue and fixed it by installing an older version of kahoot.js.

`npm i kahoot.js-updated@2.4.0`
